# Generated by Django 5.0.1 on 2024-01-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo')),
                ('category', models.CharField()),
                ('price_per_unit', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'milk',
                'verbose_name_plural': 'milks',
                'ordering': ['description'],
            },
        ),
    ]
