# Generated by Django 5.0.1 on 2024-02-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'bread',
                'verbose_name_plural': 'bread',
                'ordering': ['description'],
            },
        ),
    ]
